name: controlcenter
version: 0.1
main: me.tekkitnerds.controlcenter.controlcenter
author: Niklas Kamenisch & Aaron Braun
website: tekkit-nerds.net
commands:
     cc:
          description: Befehle für unser Plugin
          usage: /<command>
     regelbuch:
          description: Unser Regelbuch
          usage: /<command>