name: controlcenter
version: 0.1
main: me.tekkitnerds.controlcenter.controlcenter
author: Niklas Kamenisch & Aaron Braun
website: tekkit-nerds.net
commands:
     gebiet:
          description: Befehl für Gebiete
          usage: /<command>
     regelbuch:
          description: Unser Regelbuch
          usage: /<command>
     benutzer:
          description: Diverse Benutzer befehle
          usage: /<command>